services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      SIGNUPS_ALLOWED: "true" # Deactivate this with "false" after you have created your account
    volumes:
      - ./vw-data:/data 
    ports:
      - 11001:80
