services:
  gotify:
    image: gotify/server
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      GOTIFY_DEFAULTUSER_NAME: 'admin'
    volumes:
      - './gotify_data:/app/data'
